name = "claude-code-monitor"
main = "src/index.js"
compatibility_date = "2024-12-20"

[env.production]
vars = { SEND_ERROR_NOTIFICATIONS = "true" }

[[kv_namespaces]]
binding = "CLAUDE_CODE_KV"
id = "YOUR_KV_NAMESPACE_ID"

[triggers]
crons = ["*/15 * * * *"]

# Environment variables to be set:
# TELEGRAM_BOT_TOKEN - Your Telegram bot token
# TELEGRAM_CHAT_ID - Your Telegram chat ID